default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DEVELOPMENT_DATABASE", "devpolish") %>
test: &test
  <<: *default
  database: administrator-rails_test
production:
  <<: *default
  database: administrator-rails
  username: administrator-rails
  password: <%= ENV['ADMINISTRATOR-RAILS_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
